export type SeedProduct = {
  id: string;
  name: string;
  brand: string;
  category: string;
  description: string;
  priceCents: number;
  calories: number;
  proteinGrams: number;
  servingSize: string;
  externalUrl: string;
};

export const products: SeedProduct[] = [
  {
    id: "quest-chocolate-chip-cookie-dough-bar",
    name: "Chocolate Chip Cookie Dough Protein Bar",
    brand: "Quest Nutrition",
    category: "Snack Bars",
    description:
      "A protein bar with 21g of protein and 1g of sugar in a chocolate chip cookie dough flavor.",
    priceCents: 267,
    calories: 200,
    proteinGrams: 21,
    servingSize: "1 bar (60g)",
    externalUrl: "https://www.questnutrition.com/products/protein-bars",
  },
  {
    id: "rxbar-chocolate-sea-salt",
    name: "Chocolate Sea Salt RXBAR",
    brand: "RXBAR",
    category: "Snack Bars",
    description:
      "A whole-food protein bar made with egg whites, dates, and nuts in chocolate sea salt flavor.",
    priceCents: 233,
    calories: 210,
    proteinGrams: 12,
    servingSize: "1 bar (52g)",
    externalUrl: "https://shop.rxbar.com/shop/protein-bars.html",
  },
  {
    id: "perfect-bar-peanut-butter",
    name: "Peanut Butter Perfect Bar",
    brand: "Perfect Bar",
    category: "Snack Bars",
    description:
      "A refrigerated peanut butter protein bar made with whole food ingredients and organic honey.",
    priceCents: 299,
    calories: 350,
    proteinGrams: 17,
    servingSize: "1 bar (65g)",
    externalUrl: "https://perfectsnacks.com/",
  },
  {
    id: "kind-peanut-butter-dark-chocolate-protein-bar",
    name: "Peanut Butter Dark Chocolate Protein Bar",
    brand: "KIND",
    category: "Snack Bars",
    description: "A protein bar made from real food ingredients with 12g of plant protein.",
    priceCents: 229,
    calories: 250,
    proteinGrams: 12,
    servingSize: "1 bar (50g)",
    externalUrl: "https://www.kindsnacks.com/protein-bars",
  },
  {
    id: "one-bar-peanut-butter-cup",
    name: "Peanut Butter Cup ONE Bar",
    brand: "ONE Brands",
    category: "Snack Bars",
    description:
      "A layered protein bar with 20g of protein and 1g of sugar in peanut butter cup flavor.",
    priceCents: 249,
    calories: 220,
    proteinGrams: 20,
    servingSize: "1 bar (60g)",
    externalUrl: "https://www.one1brands.com/",
  },
  {
    id: "orgain-chocolate-chip-cookie-dough-protein-bar",
    name: "Chocolate Chip Cookie Dough Organic Protein Bar",
    brand: "Orgain",
    category: "Snack Bars",
    description:
      "An organic plant-based protein bar with 10g of protein and 5g of prebiotic fiber.",
    priceCents: 200,
    calories: 200,
    proteinGrams: 10,
    servingSize: "1 bar (45g)",
    externalUrl: "https://orgain.com/collections/protein-bar",
  },
  {
    id: "gomacro-peanut-butter-chocolate-chip-macrobar",
    name: "Peanut Butter Chocolate Chip MacroBar",
    brand: "GoMacro",
    category: "Snack Bars",
    description:
      "An organic vegan protein bar made with brown rice protein and organic nut butter.",
    priceCents: 300,
    calories: 250,
    proteinGrams: 11,
    servingSize: "1 bar (50g)",
    externalUrl: "https://gomacro.com/collections/macrobars",
  },
  {
    id: "aloha-chocolate-chip-cookie-dough-protein-bar",
    name: "Chocolate Chip Cookie Dough Protein Bar",
    brand: "ALOHA",
    category: "Snack Bars",
    description:
      "An organic plant-based protein bar with 14g of protein and 5g or less of sugar.",
    priceCents: 292,
    calories: 230,
    proteinGrams: 14,
    servingSize: "1 bar (54g)",
    externalUrl: "https://aloha.com/collections/protein-bars",
  },
  {
    id: "quest-sour-cream-onion-protein-chips",
    name: "Sour Cream & Onion Protein Chips",
    brand: "Quest Nutrition",
    category: "Protein Snacks",
    description: "A baked crunchy chip snack with 21g of protein per bag.",
    priceCents: 287,
    calories: 130,
    proteinGrams: 21,
    servingSize: "1 bag (32g)",
    externalUrl: "https://www.questnutrition.com/products/protein-chips",
  },
  {
    id: "quest-chocolate-chip-protein-cookie",
    name: "Chocolate Chip Protein Cookie",
    brand: "Quest Nutrition",
    category: "Protein Snacks",
    description: "A soft-baked cookie with 15g of protein and 1g of sugar per cookie.",
    priceCents: 250,
    calories: 220,
    proteinGrams: 15,
    servingSize: "1 cookie (59g)",
    externalUrl: "https://www.questnutrition.com/collections/protein-cookies",
  },
  {
    id: "lenny-larrys-chocolate-chip-complete-cookie",
    name: "Chocolate Chip The Complete Cookie",
    brand: "Lenny & Larry's",
    category: "Protein Snacks",
    description: "A vegan protein cookie with 16g of plant protein and 10g of fiber.",
    priceCents: 204,
    calories: 400,
    proteinGrams: 16,
    servingSize: "1 cookie (113g)",
    externalUrl: "https://www.lennylarry.com/collections/the-complete-cookie",
  },
  {
    id: "epic-bison-bacon-bites",
    name: "Bison & Uncured Bacon Meat Bites",
    brand: "EPIC Provisions",
    category: "Protein Snacks",
    description: "Bite-sized savory meat snacks made from bison and uncured bacon.",
    priceCents: 349,
    calories: 130,
    proteinGrams: 12,
    servingSize: "1 pouch (36g)",
    externalUrl: "https://epicprovisions.com/collections/bites",
  },
  {
    id: "wilde-chicken-waffles-protein-chips",
    name: "Chicken & Waffles Protein Chips",
    brand: "Wilde Brands",
    category: "Protein Snacks",
    description: "A crispy chip made from chicken breast, egg whites, and bone broth.",
    priceCents: 199,
    calories: 110,
    proteinGrams: 12,
    servingSize: "1 bag (23g)",
    externalUrl: "https://www.wildebrands.com/collections/shop-all",
  },
  {
    id: "genius-gourmet-cheddar-cheese-protein-puffs",
    name: "Cheddar Cheese Protein Puffs",
    brand: "Genius Gourmet",
    category: "Protein Snacks",
    description: "A crunchy gluten-free puff snack delivering 15g of protein per bag.",
    priceCents: 375,
    calories: 130,
    proteinGrams: 15,
    servingSize: "1 bag (28g)",
    externalUrl: "https://www.geniusgourmet.com/products/protein-puffs",
  },
  {
    id: "4505-classic-chili-salt-chicharrones",
    name: "Classic Chili & Salt Chicharrones",
    brand: "4505 Meats",
    category: "Protein Snacks",
    description:
      "A fried pork rind snack seasoned with chili and salt, naturally high in protein and carb-free.",
    priceCents: 249,
    calories: 80,
    proteinGrams: 9,
    servingSize: "1 oz (28g)",
    externalUrl: "https://4505meats.com/",
  },
  {
    id: "chomps-original-beef-stick",
    name: "Original Beef Stick",
    brand: "Chomps",
    category: "Jerky",
    description: "A 100% grass-fed beef snack stick with 10g of protein and 0g of sugar.",
    priceCents: 256,
    calories: 100,
    proteinGrams: 10,
    servingSize: "1 stick (28g)",
    externalUrl: "https://chomps.com/collections/beef-jerky",
  },
  {
    id: "country-archer-original-beef-jerky",
    name: "Original Beef Jerky",
    brand: "Country Archer",
    category: "Jerky",
    description: "Handcrafted jerky made from 100% grass-fed beef with 9g of protein per serving.",
    priceCents: 599,
    calories: 70,
    proteinGrams: 9,
    servingSize: "1 oz (28g)",
    externalUrl: "https://shop.countryarcher.com/products/original-beef-jerky",
  },
  {
    id: "jacklinks-original-beef-jerky",
    name: "Original Beef Jerky",
    brand: "Jack Link's",
    category: "Jerky",
    description: "Classic slow-smoked 100% beef jerky with 11g of protein per serving.",
    priceCents: 599,
    calories: 80,
    proteinGrams: 11,
    servingSize: "1 oz (28g)",
    externalUrl: "https://www.jacklinks.com/products/original-beef-jerky",
  },
  {
    id: "peoples-choice-old-fashioned-original-beef-jerky",
    name: "Old Fashioned Original Beef Jerky",
    brand: "People's Choice",
    category: "Jerky",
    description: "Thick-cut, handcrafted beef jerky made with 100% USA Angus beef.",
    priceCents: 699,
    calories: 80,
    proteinGrams: 13,
    servingSize: "1 oz (28g)",
    externalUrl: "https://peopleschoicebeefjerky.com/products/old-fashioned-original",
  },
  {
    id: "epic-wagyu-beef-snack-strips",
    name: "Wagyu Beef Snack Strips",
    brand: "EPIC Provisions",
    category: "Jerky",
    description: "Thin snack strips made from 100% grass-fed wagyu beef with honey and spices.",
    priceCents: 215,
    calories: 30,
    proteinGrams: 5,
    servingSize: "1 strip (10g)",
    externalUrl: "https://epicprovisions.com/collections/snack-strips",
  },
  {
    id: "vermont-smoke-cure-original-beef-pork-sticks",
    name: "Original Beef & Pork Sticks",
    brand: "Vermont Smoke & Cure",
    category: "Jerky",
    description:
      "Hardwood-smoked meat sticks made from humanely raised beef and pork with no antibiotics.",
    priceCents: 204,
    calories: 80,
    proteinGrams: 7,
    servingSize: "1 stick (28g)",
    externalUrl: "https://store.vermontsmokeandcure.com/collections/all",
  },
  {
    id: "oberto-original-grass-fed-beef-stick",
    name: "Original Grass Fed Beef Stick",
    brand: "Oberto",
    category: "Jerky",
    description: "A clean-protein snack stick made from 100% grass-fed beef.",
    priceCents: 212,
    calories: 100,
    proteinGrams: 8,
    servingSize: "1 stick (28g)",
    externalUrl: "https://www.oberto.com/",
  },
  {
    id: "golden-island-korean-bbq-pork-jerky",
    name: "Korean Barbecue Pork Jerky",
    brand: "Golden Island",
    category: "Jerky",
    description: "Fire-grilled pork jerky marinated in a Korean barbecue-style recipe.",
    priceCents: 599,
    calories: 80,
    proteinGrams: 7,
    servingSize: "1 oz (28g)",
    externalUrl: "https://www.goldenislandjerky.com/shop/korean-barbecue-pork-jerky",
  },
  {
    id: "premier-protein-chocolate-shake",
    name: "Chocolate Protein Shake",
    brand: "Premier Protein",
    category: "Shakes & Protein Powders",
    description: "A ready-to-drink shake with 30g of protein, 160 calories, and 1g of sugar.",
    priceCents: 250,
    calories: 160,
    proteinGrams: 30,
    servingSize: "1 bottle (11.5 fl oz)",
    externalUrl: "https://www.premierprotein.com/products/chocolate-protein-shake",
  },
  {
    id: "core-power-chocolate-42g-shake",
    name: "Chocolate Protein Shake 42g",
    brand: "Fairlife Core Power",
    category: "Shakes & Protein Powders",
    description: "An ultra-filtered milk protein shake with 42g of protein for post-workout recovery.",
    priceCents: 349,
    calories: 230,
    proteinGrams: 42,
    servingSize: "1 bottle (14 fl oz)",
    externalUrl: "https://fairlife.com/core-power/chocolate-protein-shake-42g/",
  },
  {
    id: "owyn-dark-chocolate-protein-shake",
    name: "Dark Chocolate Protein Shake",
    brand: "OWYN",
    category: "Shakes & Protein Powders",
    description: "A dairy-free plant protein shake with 20g of protein and allergen-friendly ingredients.",
    priceCents: 325,
    calories: 150,
    proteinGrams: 20,
    servingSize: "1 bottle (12 fl oz)",
    externalUrl: "https://liveowyn.com/collections/protein-shakes",
  },
  {
    id: "kachava-chocolate-shake",
    name: "Chocolate All-in-One Nutrition Shake",
    brand: "Ka'Chava",
    category: "Shakes & Protein Powders",
    description:
      "A plant-based meal replacement shake blending 25g of protein with superfoods, adaptogens, and probiotics.",
    priceCents: 280,
    calories: 240,
    proteinGrams: 25,
    servingSize: "2 scoops (70g)",
    externalUrl: "https://www.kachava.com/",
  },
  {
    id: "ritual-essential-protein-chocolate",
    name: "Essential Protein Daily Shake Chocolate",
    brand: "Ritual",
    category: "Shakes & Protein Powders",
    description: "A plant-based pea protein powder with a complete amino acid profile in chocolate flavor.",
    priceCents: 235,
    calories: 130,
    proteinGrams: 20,
    servingSize: "5 tbsp (31g)",
    externalUrl: "https://ritual.com/products/essential-protein-daily-shake-18-chocolate",
  },
  {
    id: "vega-protein-recovery-chocolate",
    name: "Protein + Recovery Chocolate",
    brand: "Vega",
    category: "Shakes & Protein Powders",
    description: "A plant-based protein powder with 30g of protein and 5g of BCAAs for post-workout recovery.",
    priceCents: 342,
    calories: 190,
    proteinGrams: 30,
    servingSize: "1 scoop (44g)",
    externalUrl: "https://myvega.com/collections/protein-powders",
  },
  {
    id: "orgain-30g-protein-shake-vanilla-bean",
    name: "30g Protein Shake Vanilla Bean",
    brand: "Orgain",
    category: "Shakes & Protein Powders",
    description: "A ready-to-drink organic protein shake with 30g of protein per bottle.",
    priceCents: 300,
    calories: 250,
    proteinGrams: 30,
    servingSize: "1 bottle (14 fl oz)",
    externalUrl: "https://orgain.com/collections/protein-shakes",
  },
  {
    id: "optimum-nutrition-gold-standard-whey",
    name: "Gold Standard 100% Whey Double Rich Chocolate",
    brand: "Optimum Nutrition",
    category: "Shakes & Protein Powders",
    description: "A whey protein isolate powder delivering 24g of protein and 5.5g of BCAAs per scoop.",
    priceCents: 190,
    calories: 120,
    proteinGrams: 24,
    servingSize: "1 scoop (30g)",
    externalUrl: "https://www.optimumnutrition.com/en-us/products/gold-standard-100-whey-protein-powder",
  },
  {
    id: "nature-made-multivitamin-with-iron",
    name: "Multivitamin Tablets with Iron",
    brand: "Nature Made",
    category: "Vitamins & Supplements",
    description: "A daily multivitamin tablet providing 23 key nutrients including iron.",
    priceCents: 1399,
    calories: 0,
    proteinGrams: 0,
    servingSize: "1 tablet",
    externalUrl: "https://www.naturemade.com/collections/multivitamins",
  },
  {
    id: "thorne-multi-vitamin-elite",
    name: "Multi-Vitamin Elite",
    brand: "Thorne",
    category: "Vitamins & Supplements",
    description: "An NSF Certified for Sport A.M./P.M. multivitamin system supporting energy and recovery.",
    priceCents: 6800,
    calories: 0,
    proteinGrams: 0,
    servingSize: "2 capsules AM + 2 capsules PM",
    externalUrl: "https://www.thorne.com/explore/multi-vitamin-elite",
  },
  {
    id: "ritual-essential-for-women-multivitamin",
    name: "Essential for Women 18+ Multivitamin",
    brand: "Ritual",
    category: "Vitamins & Supplements",
    description: "A daily multivitamin with traceable nutrients formulated to fill common dietary gaps for women.",
    priceCents: 3300,
    calories: 0,
    proteinGrams: 0,
    servingSize: "2 capsules",
    externalUrl: "https://ritual.com/products/essential-for-women-multivitamin",
  },
  {
    id: "optimum-nutrition-opti-men",
    name: "Opti-Men Multivitamin",
    brand: "Optimum Nutrition",
    category: "Vitamins & Supplements",
    description: "A multivitamin system providing 30+ active ingredients across 4 blends for active men.",
    priceCents: 3299,
    calories: 0,
    proteinGrams: 0,
    servingSize: "3 tablets",
    externalUrl: "https://www.optimumnutrition.com/en-us/products/opti-men-multivitamin",
  },
  {
    id: "carlson-very-finest-fish-oil",
    name: "The Very Finest Fish Oil",
    brand: "Carlson Labs",
    category: "Vitamins & Supplements",
    description: "A liquid omega-3 fish oil supplement providing 1,600mg of omega-3s per serving.",
    priceCents: 3990,
    calories: 40,
    proteinGrams: 0,
    servingSize: "1 tsp (5mL)",
    externalUrl: "https://www.carlsonlabs.com/products/the-very-finest-fish-oil",
  },
  {
    id: "megafood-womens-advanced-multivitamin",
    name: "Women's Advanced Multivitamin",
    brand: "MegaFood",
    category: "Vitamins & Supplements",
    description: "A whole-food multivitamin with 15mg of iron and methylated B vitamins for women.",
    priceCents: 3099,
    calories: 0,
    proteinGrams: 0,
    servingSize: "2 tablets",
    externalUrl: "https://megafood.com/products/multi-for-women",
  },
  {
    id: "natures-bounty-vitamin-d3-5000iu",
    name: "Vitamin D3 5000 IU",
    brand: "Nature's Bounty",
    category: "Vitamins & Supplements",
    description: "A rapid-release softgel supplement supporting bone, teeth, and immune health.",
    priceCents: 1299,
    calories: 0,
    proteinGrams: 0,
    servingSize: "1 softgel",
    externalUrl: "https://naturesbounty.com/products/vitamin-d3-5000-iu-240-rapid-release-softgels",
  },
  {
    id: "vital-proteins-collagen-peptides",
    name: "Collagen Peptides Unflavored",
    brand: "Vital Proteins",
    category: "Superfoods & Powders",
    description: "An unflavored collagen powder providing 20g of collagen peptides from grass-fed bovine hide.",
    priceCents: 2700,
    calories: 70,
    proteinGrams: 18,
    servingSize: "2 scoops (20g)",
    externalUrl: "https://www.vitalproteins.com/products/vp-collagen-peptides",
  },
  {
    id: "amazing-grass-super-greens-original",
    name: "Super Greens Original",
    brand: "Amazing Grass",
    category: "Superfoods & Powders",
    description: "A greens powder blend of 14 organic greens, fruits, and vegetables with 1 billion CFU probiotics.",
    priceCents: 2699,
    calories: 30,
    proteinGrams: 2,
    servingSize: "1 scoop (8g)",
    externalUrl: "https://amazinggrass.com/products/greens-blend-the-original",
  },
  {
    id: "navitas-organics-cacao-powder",
    name: "Organic Cacao Powder",
    brand: "Navitas Organics",
    category: "Superfoods & Powders",
    description: "An unsweetened, minimally processed organic cacao powder rich in antioxidants and minerals.",
    priceCents: 1499,
    calories: 25,
    proteinGrams: 2,
    servingSize: "1 tbsp (6g)",
    externalUrl: "https://navitasorganics.com/products/cacao-powder",
  },
  {
    id: "four-sigmatic-focus-matcha-latte",
    name: "Focus Matcha Latte with Lion's Mane",
    brand: "Four Sigmatic",
    category: "Superfoods & Powders",
    description: "A ceremonial-grade matcha blend with lion's mane mushroom extract for focus support.",
    priceCents: 3800,
    calories: 25,
    proteinGrams: 0,
    servingSize: "1 packet (7g)",
    externalUrl: "https://us.foursigmatic.com/products/focus-matcha-latte-box",
  },
  {
    id: "bloom-nutrition-greens-superfoods",
    name: "Greens & Superfoods Mango",
    brand: "Bloom Nutrition",
    category: "Superfoods & Powders",
    description: "A greens powder blend of 38 ingredients including barley grass, spirulina, prebiotics, and digestive enzymes.",
    priceCents: 3399,
    calories: 25,
    proteinGrams: 1,
    servingSize: "1 scoop (8g)",
    externalUrl: "https://bloomnu.com/products/greens-superfoods",
  },
  {
    id: "laird-superfood-organic-prebiotic-daily-greens",
    name: "Organic Prebiotic Daily Greens",
    brand: "Laird Superfood",
    category: "Superfoods & Powders",
    description: "An organic greens powder with prebiotics designed for daily digestive and energy support.",
    priceCents: 3900,
    calories: 20,
    proteinGrams: 1,
    servingSize: "1 scoop (7g)",
    externalUrl: "https://lairdsuperfood.com/collections/all",
  },
  {
    id: "orgain-organic-superfoods-powder",
    name: "Organic Superfoods Powder Original",
    brand: "Orgain",
    category: "Superfoods & Powders",
    description: "An organic greens powder with 50 superfoods and 1 billion probiotics per serving.",
    priceCents: 3299,
    calories: 45,
    proteinGrams: 2,
    servingSize: "1 scoop (8g)",
    externalUrl: "https://orgain.com/products/organic-superfoods-powder",
  },
];
